// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwJMWsfK1WkLBeF38yMB6HvzsfvjKrE6Q',
    appId: '1:720570909629:android:f9d65ba5dcbded239288d4',
    messagingSenderId: '720570909629',
    projectId: 'farmwise-93a2e',
    storageBucket: 'farmwise-93a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52pVg-lqXfNlwRnxrNy705q3HDDGccys',
    appId: '1:720570909629:ios:041c71c9207ad52b9288d4',
    messagingSenderId: '720570909629',
    projectId: 'farmwise-93a2e',
    storageBucket: 'farmwise-93a2e.firebasestorage.app',
    iosClientId: '720570909629-jp7dmqa7utmji9j7p3sru9e7bfhj26bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmWise',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNOtUKQxjnPxmd64iOaT7XcvmdEr_xfcU',
    appId: '1:720570909629:web:6d2223197b1a96079288d4',
    messagingSenderId: '720570909629',
    projectId: 'farmwise-93a2e',
    authDomain: 'farmwise-93a2e.firebaseapp.com',
    storageBucket: 'farmwise-93a2e.firebasestorage.app',
  );

}